### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [JanmanX/bearable-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a LICENSE - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by JanmanX** [comment]
A LICENSE file added. 

Thanks for considering my small theme for inclusion in your repository. Please let me know if there is anything more I can do! :)
